CashOperationsHistoryWriterJob:
    Db:
        LogsConnString:
            settings-key: LogsConnString
            types:
                - AzureTableStorage
        DataConnString:
            settings-key: CashOperationsHistoryWriterJob-DataConnString
            types:
                - AzureTableStorage
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl